services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
